@startmindmap
* Power ON
** BIOS
*** Master boot record (MBR)
**** Boot Loader (GRUB)
***** Kernel (Linux OS)
****** Inital Ram disk - initramfs 
******* /sbin/init (parent process)
******** X Windows System
@endmindmap